language: ruby
before_script:
- pip install --user awscli
- rm -rf public
- bundle exec jekyll build
script:
- aws s3 sync public/ s3://awesomestaticsites.com --acl public-read --delete
- aws cloudfront create-invalidation --distribution-id EARBDS8R4QWRW --paths '/*'
branches:
 only:
 - master
