language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: ON0zKW6ejIUXK4iHLnlchPI6O98qRAWCv7HgLkwodqmAYmXDkrHA9tXadL3VeyFUGpSeg3Sdtyt2902zPfXa/2n2Mvk/E1ycOYyQ2mxGGDHM0sqU9n9VGOaQ7RBWXWxuoVBQqX+8YqanJCDL9du6RVjErRsm6FHaSA5T3dt67edJMavsEkv32+1m06EkI+Ft2g/gjcd3Yt8eu7u7NXFGwR1f1a8ap2RaKFRO4PTFE42M4Kx80BptRHSwB4FlFCd+19OX3Vr1WKjygGAO5k+d7NrQnIk1PrzgZ/ivAyClhD2876da5o8j04PE1qQywz2t65mkOxOH4ypHYI5SY+E0wIcIJrzsfeYqyli10lqg1dPscbL6vWD/7gV4m3c1r1oypkeBQdA6CJhBT6Um6X1aCSWjluVRlUpJ6B8i24HmIyt9a+JpB6BHPql27Eo1j5g7l3Fc4Ws/Sd058ngvhKMGIVvwwXwXOijDaalSFMDDNg62LFtruvgfb7+pnzYO7wskNigPRQMfPr3STJf15+Rb49hCEKoCIKGvLR+rroK7+lBErZoYrKQax8KweUHpqUdJTfOG5pGdNA79wK5ZWYgccHvmUKeWUHEU4sFYU+26yT3PQgyFUAc+IOppA/smTDWXZYjxTwdmkU8aMWP6r3cSyyblfQYpsIjAgdJBZA3b1OM=
  - secure: kS85PhsPOkG+QfeFnTqyFzA5jwMka54mTMhuLirfmU2dFBpe7gEiI/93EaZKuOfGDVfqz1sy1zRAeRtbfrHK2I37mxPbSidEDYoJ+a5bT71RqLX50TgbNfyEfTNyJ7kJyzAnfznO3VzithNiVKLephICnZ+LZ7Amj8fDM+WN19MO4MoXYASABEHCFw7q8A2sVeHKRjKQRZll6P9aUkHDXiccMXaKRbh1KqRyoyrrv4yRS3xgi+kkSznUBE/J9l8B3QZXq2VvPxUusoXNuFJs/kntoEb9Tw+/jruv59rJERMNXfmqrg3Zr6ta7BXpubQaDUEAPihFOA+pgFtZh0GJaEIgW2raOGzmtHLJddjki5dPNgMcX7i4RFXl9u4MC9u8XifZ74ymx2Y5mFMrzmsum8T/cC6iQhMc6MD4se7fN5RkkM68UfU+ovbnTBc/uWxc3NPdGeTvwXXEJIA1EaP5XHCW52OwzfwdlpbQ4lzjBLfZD9pUfIm4+ila6LqilwVqVhTk3nECd8qY/MPp74mUOjVc5gPgeLLsQjD7QyQhilks+5tyM+kIalkS82oiCMENZcn1fMU12pwrOMsFxXPgAEe6gSiieNMEHgAYVn2O5Q7ACMuvqhGwE/gqZGZzAunAWrcRfqjr+Kru6o5PPR0T61YLPSUwvOA6/6S5Esi2Xck=
